version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn clean install
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully
      - echo "web: java -jar target/test-cicd.war" > Procfile  # Create the Procfile

artifacts:
  files:
    - target/test-cicd.war
    - Procfile  # Include the Procfile in the artifacts
  discard-paths: yes