version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn clean install
  build:
    commands:
      - echo Entered the build phase...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/test-cicd.jar

  discard-paths: yes